[project]
name = "sassyshell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.11.0",
    "scikit-learn>=1.7.2",
    "typer>=0.19.2",
]

[project.scripts]
sassysh = "sassyshell.cli:app"
